[package]
name = "browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = { version = "0.3",features = [
    "console",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "MouseEvent"
]}
js-sys = "0.3"
game = { path = "../game" }
wasm-bindgen = "0.2.74"
